sudo apt install libao-dev
sudo apt install libglew-dev
sudo apt install freeglut3-dev
sudo apt install libsigc++-2.0-dev
sudo apt install libgif-dev
sudo apt install libusb-1.0-0-dev
sudo apt install libfreetype-dev
sudo apt install libxml2-dev
sudo apt install libopenthreads-dev
sudo apt install libjpeg-dev
sudo apt install libfribidi-dev
sudo apt install mpv
